### PR TITLE
Framework for integrating database maintenance scripts

### PR DESCRIPTION
**Pull request by stdavis**
@steveoh: Wanted to get your thoughts before I worked on the rest of these...

To add new scripts you need to:
1. copy the existing folder to `database_maintenance`
1. copy/paste a new pallet.py file and update the name of the script
1. fix the paths to the `*.sde` files (see `ffsl.py` for an example)

My goal was to make it as easy as possible for @MichaelAGRC to maintain these scripts without having to jam them all into classes and do a lot of copy/pasting.

### CODE REVIEW

**Comment by steveoh** [comment]
It looks kinda funky and it doubles the amount of files necessary. I wonder if @MichaelAGRC would be opposed to jamming them into a class. Copy pasting is going to happen no matter what.

**Comment by MichaelAGRC** [comment]
I'm not opposed to learning something new.

**Comment by stdavis** [comment]
I had a feeling this would your reaction. I guess it was a good experiment.

I'll jam a few into classes as examples and then maybe @MichaelAGRC can do the rest?

**Comment by stdavis** [comment]
OK. New steps to converting a script:
1. Copy the contents of template.py
1. Put the contents of the script into the ship method (within the try/except block)
1. Update any paths to database connection files to be relative. No hard-coded paths.
1. Replace all calls to `print` with `self.log.info(...)`

If @steveoh is OK with this new method then I'll merge this PR and @MichaelAGRC can submit another one for the rest of the scripts? I'm happy to help with the GitHub stuff if you need it.

**Comment by steveoh** [comment]
Seems reasonable.

**Pull request merged**
