### PR TITLE
fix: remove dependency on Pro project

### PR DESCRIPTION
**Pull request by stdavis**
This PR removes the dependency on the Pro project for updating data in AGOL. Note that it no longer sets any tags, groups, or sharing options. Those will need to be done outside of forklift.

It depends on `SGID.META.AGOLItems` to define the relationship between tables in the new internal SGID database and their corresponding AGOL items. It will only attempt to update AGOL for feature classes that have an AGOL id value populated.

A big thanks goes out to @jacobdadams for finding the `overwrite` api.

### CODE REVIEW

**Comment by stdavis** [comment]
I added `SGID.sde` to the forklift garage folder on 57.

**Comment by stdavis** [comment]
I just realized that this may add the `FORKLIFT_HASH` field to the AGOL data since the destination is staging. This field is present in my test AGOL data. Is that a bad thing? I wonder if it hurts anything and perhaps if some might find it useful for doing change detection on their end.

**Comment by stdavis** [comment]
I spoke with @MichaelAGRC about the `FORKLIFT_HASH` field showing up in AGOL and our thoughts are that it doesn't hurt anything and may even be helpful for someone at some point. So I'm good with leaving it. Let me know if anyone else feels differently...

**Comment by steveoh** [comment]
My thoughts are that the hash is an internal detail to forklift and will not be useful to anything other than forklift. I vote to remove it. 

Unless we started to use the hash as a global id and could do feature level updates... 🤔

**Comment by stdavis** [comment]
> this looks way less complicated to me at the price of thumbnails, tags, and sharing.

I see these being managed in a separate project outside of forklift. Symbology would also be included in this consideration. I did test and validate that updating the data via this new method does not overwrite or affect these other item properties in any way that I could see.

**Comment by stdavis** [comment]
> there are two variables that don't seem to follow our naming conventions.

Fixed via f8a757e. Thanks for the catch.

**Comment by stdavis** [comment]
I'm not sure if this should be merged or if we should just wait for the official switch over from SGID10 to SGID internal. My only concern with waiting is the potential for more issues creating duplicate AGOL items with the current pallet.

**Comment by stdavis** [comment]
> do you want to remove the current pallet from forklift for a short while?

That may be the safest solution. @MichaelAGRC Are you OK if we just disable the AGOL pallet until the switch over from SGID10 to SGID as the source of truth? That way we won't run the risk of creating duplicate items before this new pallet is merged.

**Comment by stdavis** [comment]
I deleted `AGOLPallet.py` from the server this morning. We can merge this PR and put it back on the switch over day next week.

**Comment by stdavis** [comment]
Forgot to merge this yesterday...

**Pull request merged**
